### PR TITLE
Added feature of Name and DOB adding

### PR DESCRIPTION
**Pull request by The-vipul-kaushik**

### CODE REVIEW

**Review by chaudhary19 — CHANGES_REQUESTED** [review]
I guess there is no need to write the following line:
 if n > 0:

you can delete this line, otherwise, everything is okay

**Comment by The-vipul-kaushik** [comment]
Ok ok
I'll do it

**Comment by The-vipul-kaushik** [comment]
Do I have pull request again or will it be visible only by commit??
I have committed it.

**Comment by chaudhary19** [comment]
just commit it again
________________________________

**Comment by chaudhary19** [comment]
Please once see the excel file attached and take the input of all the required values to be stored
________________________________

**Comment by The-vipul-kaushik** [comment]
Can you please brief about the year column in excel sheet?
What does it signifies?

**Comment by The-vipul-kaushik** [comment]
I have added input for all attributes.

**Review by chaudhary19 — APPROVED** [review]

**Pull request merged**
